### ISSUE TITLE
x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by josephspurrier** [tstranex/u2f#14]
Using Chrome 66, we are not longer able to call: u2f.Register. We can login fine, but the registration fails. Is anyone else experiencing the same thing?

**Comment by erincandescent** [comment]
Chrome 66 has disabled attestation by default.

You need to either add `'attestation': 'direct'` to the RegisterRequest you pass to u2f.register on the client (which will cause a permissions prompt), or disable attestation certificate checking

**Comment by tstranex** [comment]
The u2fdemo has now been updated to disable attestation certificate checking by default.
