### ISSUE TITLE
/bin/bash: gtkdoc-mktmpl: command not found

### ISSUE THREAD

**Issue by perry-amsterdam** [tstranex/u2f#16]
Hi,
While compiling the code, i get the following error message:
 DOC   Rebuilding template files
/bin/bash: gtkdoc-mktmpl: command not found
Makefile:812: recipe for target 'tmpl-build.stamp' failed
make[2]: *** [tmpl-build.stamp] Error 127
make[2]: Leaving directory '/root/libu2f-host/gtk-doc'
Makefile:641: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/libu2f-host'
Makefile:552: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AllensLeng** [comment]
啊啊啊
