### ISSUE TITLE
License clarity

### ISSUE THREAD

**Issue by brianmhunt** [tstranex/u2f#2]
The README and LICENSE for the repository are MIT.  However, the files themselves say "all rights reserved" ("ARR").  Those are incompatible; the ARR should be removed if the intention is to license the code under the MIT terms.

Cheers.

**Comment by tstranex** [comment]
The file headers have been updated to include the text "Use of this source code is governed by the MIT license that can be found in the LICENSE file." which should clarify any licensing doubts.

**Comment by brianmhunt** [comment]
Awesome, cheers @tstranex
