### ISSUE TITLE
*Registration.Authenticate should return dedicated error types

### ISSUE THREAD

**Issue by kardianos** [tstranex/u2f#6]
Per conversation at: https://github.com/Yubico/php-u2flib-server/issues/5#issuecomment-69514885

applications should be specifically aware if the provided counter is too low.  The application may want to disable the account or raise a specific event to the larger security structure.

I recommend something like:

```
var (
  ErrCounterLow = errors.New("u2f: counter not increasing")
)
```

Then return that error in the counter check.

**Comment by tstranex** [comment]
Thanks for the note. That sounds solution sounds reasonable. The library now exposes ErrCounterTooLow.
