### ISSUE TITLE
u2f.Register error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by sunderipranata** [tstranex/u2f#8]
I'm a student researching the current new authentication technology FIDO, please help.

I tried to run the example, everything is fine until the authentication through yubikey, until the javascript sending the POST request to the server to sign the challenge.
But the server returns error 500 because of the **u2f.Register error: x509: certificate signed by unknown authority** Error. 

This is the log in the browser:
Object {registrationData: "BQTwrTCRkOgUqTX9biuxvzpcowTbLUoNrwhuy87skfQ5cUfUz7…Up5wIgOkV3RF_k3INbPfEsAa4ay-7k96FUFe5tZns3YTDbIsk", version: "U2F_V2", challenge: "mK7SSh-n9wicGkBM2hX5RlgD45p6tkZfZajeCSrl-2E", appId: "https://localhost:3483", clientData: "eyJ0eXAiOiJuYXZpZ2F0b3IuaWQuZmluaXNoRW5yb2xsbWVudC…vY2FsaG9zdDozNDgzIiwiY2lkX3B1YmtleSI6InVudXNlZCJ9"}
jquery-1.11.2.min.js:4 POST https://localhost:3483/registerResponse 500 ()

This is the log in the server:
2016/12/05 17:40:02 registerRequest: &{Version:U2F_V2 Challenge:mK7SSh-n9wicGkBM2hX5RlgD45p6tkZfZajeCSrl-2E AppID:https://localhost:3483}
2016/12/05 17:40:15 u2f.Register error: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Yubico U2F Root CA Serial 457200631")

Thank you very much!! Any help is appreciated!

**Comment by tstranex** [comment]
Hi @sunderipranata 

Could you try setting SkipAttestationVerify=true in the Config parameter to Register? That will disable attestation certificate validation. If that works, it indicates that the attestation certification of your token is currently whitelisted. If it doesn't work, then it indicates a different problem. :)

**Comment by p-kraszewski** [comment]
Same error, same CA key (device is _YubiKey Neo_)
`2017/02/03 07:14:41 u2f.Register error: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Yubico U2F Root CA Serial 457200631")`

They key mentioned is available at [Yubico](https://developers.yubico.com/U2F/yubico-u2f-ca-certs.txt) and is the same as one in [certs.go](https://github.com/tstranex/u2f/certs.go) at `yubicoRootCert`. Cert is not expired (valid to 2050) and has no other symptoms of invalidity. Token is used daily, including GitHub and Google.

u2fdemo works after suggested modification:
```
...
 cfg := &u2f.Config{
   SkipAttestationVerify: true,
 }
 reg, err := u2f.Register(regResp, *challenge, cfg)
...
```

**Comment by stephen-soltesz** [comment]
After I confirmed that my yubikey is one with broken attestation certs, these references helped me figure out how to modify `tstranex/u2f/register.go`:

* [confirmation of the cause](https://github.com/briansmith/webpki/pull/34#issuecomment-273727506)
* [php server fixcerts](https://github.com/Yubico/php-u2flib-server/blob/cf369714d86e20e00372337cfcbf04dbc6d3932d/src/u2flib_server/U2F.php#L84)
* [python server fixcerts](https://github.com/Yubico/python-u2flib-server/blob/6598c0b6f6e63e8c2357f46c6dc6db2108a2de9b/u2flib_server/model.py#L66)
* [java server fixcerts](https://github.com/Yubico/java-u2flib-server/blob/a09c9f82ee3e92f5348b9ccd9640e73b395ce3cd/u2flib-server-core/src/main/java/com/yubico/u2f/data/messages/key/util/CertificateParser.java#L46)

Between lines https://github.com/tstranex/u2f/blob/c46b9c6b15141e1c75d096258e560996b68ef8cb/register.go#L126-L127 add:
```
buf[len(buf)-257] = 0
```
